# Generated by Django 3.1.4 on 2021-10-12 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20211008_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='quality',
            field=models.IntegerField(default=0),
        ),
    ]
