# Generated by Django 3.1.4 on 2021-11-25 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20211028_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-date_time']},
        ),
    ]
