# Generated by Django 3.1.4 on 2021-10-29 00:10

import device.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, default=device.models.get_default_product_image, null=True, upload_to=device.models.get_product_image_filepath),
        ),
        migrations.AddField(
            model_name='device',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=device.models.get_product_image_filepath),
        ),
    ]
