# Generated by Django 3.1.4 on 2021-10-29 00:11

import device.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20211028_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='image',
        ),
        migrations.AlterField(
            model_name='device',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=device.models.get_product_image_filepath),
        ),
    ]
