# Generated by Django 3.1.4 on 2021-11-13 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0003_auto_20211028_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='account_id',
        ),
        migrations.AddField(
            model_name='device',
            name='account_created_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
