# Generated by Django 3.1.4 on 2021-11-13 20:18

from django.db import migrations, models
import uuid

from device.models import Device


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20211113_1217'),
    ]

    def gen_uuid(apps, schema_editor):
        for row in Device.objects.all():
            row.unique_id = uuid.uuid4()
            row.save(update_fields=['unique_id'])

    operations = [
        migrations.AddField(
            model_name='device',
            name='unique_id',
            field=models.UUIDField(
                default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(gen_uuid),

        migrations.AlterField(
            model_name='device',
            name='unique_id',
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
