# Generated by Django 3.1.4 on 2021-11-13 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0005_device_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='account_created_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='device',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
